import Testing
import Foundation
@testable import HarborUtils

// MARK: - Fixtures

private let fixtureSmallTWSwift = """
// This file was autogenerated by Shipwright. DO NOT CHANGE.
//
//  Tailwind+Classes.swift
//

public typealias TW = String

public extension TW {
    ///.flex { display: flex; }
    static var `flex`: TW {
        "flex"
    }

    ///.bg-blue-500 { background-color: rgb(59 130 246); }
    static var `bgBlue500`: TW {
        "bg-blue-500"
    }

    ///.text-white { color: rgb(255 255 255); }
    static var `textWhite`: TW {
        "text-white"
    }

    ///.hidden { display: none; }
    static var `hidden`: TW {
        "hidden"
    }

    ///.rounded-lg { border-radius: 0.5rem; }
    static var `roundedLg`: TW {
        "rounded-lg"
    }
}
"""

// MARK: - Helpers

@MainActor
private func makeTempDir() throws -> String {
    let dir = FileManager.default.temporaryDirectory
        .appendingPathComponent("HarborUtilsTests-" + UUID().uuidString).path
    try FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
    return dir
}

private func writeFile(dir: String, name: String, contents: String) throws -> String {
    let path = dir + "/" + name
    try contents.write(toFile: path, atomically: true, encoding: .utf8)
    return path
}

// MARK: - Tests

@Suite("TailwindManager — parseTWMap")
@MainActor
struct ParseTWMapTests {

    @Test("parses all entries from multi-line TW.swift format")
    func parsesAllEntries() throws {
        let dir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: dir) }

        let twPath = try writeFile(dir: dir, name: "TW.swift", contents: fixtureSmallTWSwift)
        let mgr = TailwindManager(projectDir: dir)
        let map = try mgr.parseTWMap(twSwiftPath: twPath)

        #expect(map.count == 5)
        #expect(map["flex"] == "flex")
        #expect(map["bgBlue500"] == "bg-blue-500")
        #expect(map["textWhite"] == "text-white")
        #expect(map["hidden"] == "hidden")
        #expect(map["roundedLg"] == "rounded-lg")
    }

    @Test("returns empty map for empty file")
    func emptyFile() throws {
        let dir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: dir) }

        let twPath = try writeFile(dir: dir, name: "TW.swift", contents: "// empty\n")
        let mgr = TailwindManager(projectDir: dir)
        let map = try mgr.parseTWMap(twSwiftPath: twPath)

        #expect(map.isEmpty)
    }
}

@Suite("TailwindManager — extractClassesFromSource")
@MainActor
struct ExtractClassesFromSourceTests {

    @Test("extracts only used classes, sorted, from Sources/")
    func extractsUsedSubset() throws {
        let dir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: dir) }

        let twPath = try writeFile(dir: dir, name: "TW.swift", contents: fixtureSmallTWSwift)

        let sourcesDir = dir + "/Sources"
        try FileManager.default.createDirectory(atPath: sourcesDir, withIntermediateDirectories: true)
        let source = """
        import Foundation
        struct HeroSection {
            var classes: [TW] = [TW.flex, TW.bgBlue500, TW.textWhite]
        }
        """
        _ = try writeFile(dir: sourcesDir, name: "HeroSection.swift", contents: source)

        let mgr = TailwindManager(projectDir: dir)
        let result = try mgr.extractClassesFromSource(sourcesDir: sourcesDir, twSwiftPath: twPath)

        #expect(result == true)
        let lines = try String(contentsOfFile: dir + "/.tailwind-classes.txt", encoding: .utf8)
            .split(separator: "\n").map(String.init)

        // Sorted alphabetically; only the 3 used classes
        #expect(lines == ["bg-blue-500", "flex", "text-white"])
        #expect(!lines.contains("hidden"))
        #expect(!lines.contains("rounded-lg"))
    }

    @Test("handles TW references spread across multiple files")
    func multipleFiles() throws {
        let dir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: dir) }

        let twPath = try writeFile(dir: dir, name: "TW.swift", contents: fixtureSmallTWSwift)

        let sourcesDir = dir + "/Sources"
        try FileManager.default.createDirectory(atPath: sourcesDir, withIntermediateDirectories: true)

        _ = try writeFile(dir: sourcesDir, name: "A.swift", contents: "let a = TW.flex\n")
        _ = try writeFile(dir: sourcesDir, name: "B.swift", contents: "let b = TW.hidden\n")

        let mgr = TailwindManager(projectDir: dir)
        let result = try mgr.extractClassesFromSource(sourcesDir: sourcesDir, twSwiftPath: twPath)

        #expect(result == true)
        let lines = try String(contentsOfFile: dir + "/.tailwind-classes.txt", encoding: .utf8)
            .split(separator: "\n").map(String.init)

        #expect(lines.contains("flex"))
        #expect(lines.contains("hidden"))
        #expect(lines.count == 2)
    }

    @Test("unresolved TW identifiers (in comments, not in TW.swift) are silently skipped")
    func unresolvedIdentifiersSkipped() throws {
        let dir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: dir) }

        let twPath = try writeFile(dir: dir, name: "TW.swift", contents: fixtureSmallTWSwift)

        let sourcesDir = dir + "/Sources"
        try FileManager.default.createDirectory(atPath: sourcesDir, withIntermediateDirectories: true)
        let source = """
        // TW.nonexistentClass — comment reference, not in TW.swift, silently skipped
        let a = TW.flex
        """
        _ = try writeFile(dir: sourcesDir, name: "View.swift", contents: source)

        let mgr = TailwindManager(projectDir: dir)
        let result = try mgr.extractClassesFromSource(sourcesDir: sourcesDir, twSwiftPath: twPath)

        #expect(result == true)
        let lines = try String(contentsOfFile: dir + "/.tailwind-classes.txt", encoding: .utf8)
            .split(separator: "\n").map(String.init)

        // Only 'flex' — nonexistentClass is not in TW.swift so it's dropped
        #expect(lines == ["flex"])
    }

    @Test("returns false when Sources directory has no TW references")
    func noReferences() throws {
        let dir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: dir) }

        let twPath = try writeFile(dir: dir, name: "TW.swift", contents: fixtureSmallTWSwift)

        let sourcesDir = dir + "/Sources"
        try FileManager.default.createDirectory(atPath: sourcesDir, withIntermediateDirectories: true)
        _ = try writeFile(dir: sourcesDir, name: "Empty.swift", contents: "import Foundation\n")

        let mgr = TailwindManager(projectDir: dir)
        let result = try mgr.extractClassesFromSource(sourcesDir: sourcesDir, twSwiftPath: twPath)

        #expect(result == false)
    }
}

@Suite("TailwindManager — generateFullClassList")
@MainActor
struct GenerateFullClassListTests {

    @Test("emits all classes from TW.swift, sorted")
    func emitsAllClasses() throws {
        let dir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: dir) }

        let twPath = try writeFile(dir: dir, name: "TW.swift", contents: fixtureSmallTWSwift)
        let mgr = TailwindManager(projectDir: dir)
        let result = try mgr.generateFullClassList(twSwiftPath: twPath)

        #expect(result == true)
        let lines = try String(contentsOfFile: dir + "/.tailwind-classes.txt", encoding: .utf8)
            .split(separator: "\n").map(String.init)

        // All 5 fixture classes present (sorted)
        #expect(lines.count == 5)
        #expect(lines.contains("flex"))
        #expect(lines.contains("bg-blue-500"))
        #expect(lines.contains("text-white"))
        #expect(lines.contains("hidden"))
        #expect(lines.contains("rounded-lg"))
        // Verify sorted
        #expect(lines == lines.sorted())
    }
}
